//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int exId { get; set; }
        public string exName { get; set; }
        public string exDec { get; set; }
        public string exCat { get; set; }
        public int exAmount { get; set; }
        public int catId { get; set; }
        public System.DateTimeOffset exDateTime { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
